version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - data:/var/lib/postgresql

  websockets:
    image: pickmybruin/websockets:latest
    build: websockets
    ports:
      - "8001:80"
  web:
    image: pickmybruin/backend:latest
    build: .
    command: bash initialize.sh
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - websockets
volumes:
data: